### PR TITLE
Fix the GitHub Pages deployment

### LINKED ISSUE #2: Fix deploy to GH Pages
You can remove all the hacks with hardcoding the URLs in index.html as suggested on Reddit. Instead you need to add `"homepage": "https://dvampofo.github.io/bullentin-board"` to your `package.json` as mentioned in User Guide and in the build console output. Then the next time you run `npm run build` it will be built with the correct prefix and you can deploy it. I hope this helps!

### PR DESCRIPTION
**Pull request by gaearon**
This changes the build process to follow advice in the [User Guide](https://github.com/facebookincubator/create-react-app/blob/master/packages/react-scripts/template/README.md#github-pages).

I'm removing:

* Multiple HTML files
* Hardcoded asset paths in them
* The `build` folder that shouldn't have been checked out

I'm adding:

* A `.gitignore`
* The `homepage` field which, as documented, **is required** for GH deployment to work
* A handy `npm run deploy` command to do this automatically

I hope this helps!
Fixes #2.

### CODE REVIEW

**Comment by dvampofo** [comment]
@gaearon 

Awesome and thanks for contributing. Newbie error of forgoting to remove files like `404.html` and `index_toDelete.html`  etc. As a new developer I have a couple of questions.
- Should I always include a .gitignore to my repository? and...
- Is it usually recommended to include my node_modules with a repo? They were created when I ran the build but since there was so many files, I thought it would be unnecessary to add them to the repo.

The current master branch functions fine but can I pull your request as a separate branch? Rebase and merge option? I have an functioning [demo](https://dvampofo.github.io/bullentin-board/) already and dont want to break it.

**Comment by gaearon** [comment]
> Should I always include a .gitignore to my repository?

If you want to ignore something then yes. You should generally ignore build output or dependencies and only include source code. 

> Is it usually recommended to include my node_modules with a repo?

No, they should be ignored.

> The current master branch functions fine but can I pull your request as a separate branch? 

You can if you add a remote to my repository and fetch it from command line into any branch. I can't really do something to send a PR into a different branch.

But it won't break. I tested the deployment works: https://gaearon.github.io/bullentin-board/.

**Comment by dvampofo** [comment]
@gaearon I merged your pull request but now my demo doesnt work (like I feared).  Recommendation to correct the issue?

image

**Comment by gaearon** [comment]
@dvampofo How did you deploy it?

**Comment by gaearon** [comment]
I don't see `gh-pages` branch in your repository at all.
If you follow the [user guide](https://github.com/facebookincubator/create-react-app/blob/master/packages/react-scripts/template/README.md#github-pages), it says:

> Then run:
> 
> ```
> npm run deploy
> ```

Did you do this? What output do you see?

**Comment by gaearon** [comment]
Do your [project settings](https://github.com/dvampofo/bullentin-board/settings) look like this?

screen shot 2016-11-20 at 20 00 53

It's a bit hard to help because you don't explain which steps you did and what output you saw.

**Comment by dvampofo** [comment]
@gaearon Yesterday I had manually removed files like 404.html and index_toDelete.html, index.css. 

All I did was hit 'Merge pull request'.

**Comment by gaearon** [comment]
@dvampofo 

The user guide explicitly says that in order to deploy you need to run `npm run deploy` after adding the `deploy` command to `scripts` in `package.json`.

It doesn't seem like you're following it.

Just merging a PR isn't enough, you actually need to deploy the site for it to be deployed.

**Comment by gaearon** [comment]
Run locally:

```
git pull
npm install
npm run deploy
```

Does this help?

**Comment by dvampofo** [comment]
@gaearon 

> Do your project settings look like this?

Yes, I had selected this setting when I initially uploaded the files to Github.
image

**Comment by gaearon** [comment]
They don't look like what I described. Please look at my screenshot: I suggested to use `gh-pages`.

**Comment by gaearon** [comment]
Please run `npm run deploy` first. Then the `gh-pages` setting will be enabled.

**Comment by gaearon** [comment]
I updated the [guide](https://github.com/facebookincubator/create-react-app/blob/master/packages/react-scripts/template/README.md#github-pages). If you follow it everything should work. I hope this helps!

**Comment by dvampofo** [comment]
@gaearon Umm, don't be mad, but I had to reverted your pull request to my previous version since Im not getting `git pull` to work (I started to learn how to use Git CLI a few days ago so Im searching right now what to do). Would you have to resubmit the pull request?

The good news (but maybe not) is that I managed to get `gh-pages branch` show up by simply creating `git-pages` 

image

Message I receive on Git.

image

**Comment by gaearon** [comment]
Haha I'm not mad, just trying to help you. :-) It's however hard to help when you don't post the _error messages_ and your _exact sequence of steps_. This is why I'm always one step behind: you might have missed some step but I don't know which one.

**Comment by gaearon** [comment]
What do you mean by "Im not getting git pull to work"?

**Comment by gaearon** [comment]
Why do you run `git pull https://...`? What are you trying to do?

**Comment by gaearon** [comment]
There is no such command. If you wanted to see my changes you just needed to run `git pull`. That is all. You don't need to specify URL after it, it just doesn't work this way.

**Comment by dvampofo** [comment]
@gaearon Sorry that Im not clear about my steps and making it harder for you. I guess I was thinking that `git pull` functions similar to `git clone`

**Comment by gaearon** [comment]
No worries.

The first time you run `git clone` it remembers where you cloned from. This becomes a "remote" called "origin" and git remembers it. Then you can run `git pull` and `git push` many times, and it will always pull and push from the same "origin" (that is, a repository).

When you merge a pull request, a commit is copied from my repository into yours. So your "origin" is updated. This is why you only need to run `git pull` again, and you'll get my changes.

Does this help? You can try re-reverting, or I could re-submit the PR.

**Comment by dvampofo** [comment]
@gaearon 
Ohh, it's slowly beginning to make sense to me now (and yes, as a newbie, your advice is helping)! Ok, so should I (and correct me if Im wrong)

**Option A**:
1. `git clone https://github.com/gaearon/bullentin-board.git`
2. git pull
3. npm install
4. npm run deploy

or 

**Option B**:
1.  Merge your PR.
2.  `Git clone` my repository ( https://github.com/dvampofo/bullentin-board.git )
3.  git pull
4.  npm install
5.  npm run deploy
6.  npm push (???)

**Comment by gaearon** [comment]
If you clone my repo you won't be able to make any changes so it won't be useful to you.

The second sequence is correct. Except that you don't need `npm push` (you probably meant `git push` but still). When you run `npm run deploy`, `gh-pages` script will push the build folder to `gh-pages` branch automatically. So you never need to touch `gh-pages` branch yourself.

**Comment by gaearon** [comment]
I submitted #6. After you merge it you should be able to:
1. `git pull`
2. `npm install`
3. `npm run deploy`

**Comment by gaearon** [comment]
Also your main branch is now set to `gh-pages` for some reason:
screen shot 2016-11-20 at 22 28 35

This looks wrong to me. In "Branches" section of your settings you should make `master` your main branch. But you should keep `gh-pages` your GitHub Pages setting.

**Comment by gaearon** [comment]
If you have any errors following along the way please post screenshots so I better understand what's going wrong.

**Comment by dvampofo** [comment]
> you probably meant git push

Yes. Ok I wont do a `git push`.

> Also your main branch is now set to gh-pages for some reason:
> 
> This looks wrong to me. In "Branches" section of your settings you should make master your main branch. But you should keep gh-pages your GitHub Pages setting.

I've changed it now:
image

> But you should keep gh-pages your GitHub Pages setting.

Understood! :
image

Next, I've done the following ( `git pull` and then `npm install` (it's taking long to install, Im not sure if its because Im dealing with a very large package and/or my computer is old) 

image

...right now Im waiting for `npm install` to finish...

**Comment by gaearon** [comment]
You seem to be using npm 2. I don't recommend it as it's extremely slow.
I recommend either using npm 3 (slightly faster) or Yarn (significantly faster).

**Comment by dvampofo** [comment]
> You seem to be using npm 2. I don't recommend it as it's extremely slow.

Yeah, it took ~15 mins. 

So this happened:

image

and then Github login had popped up (so I put in my username and password) when I typed `npm run deploy`. After which bash ran lines of code and gave me this:

image

and I think everything is done (?) 

and is this Yarn you're talking about: https://www.npmjs.com/package/yarn  OR https://code.facebook.com/posts/1840075619545360

**Comment by gaearon** [comment]
Looks working to me, congratulations! http://dvampofo.github.io/bullentin-board
As you can see, the commit to `gh-pages` was done automatically:

screen shot 2016-11-20 at 23 11 20

Now any time you want to deploy you can just run `npm run deploy` and that's it.

> and is this Yarn you're talking about: https://www.npmjs.com/package/yarn OR https://code.facebook.com/posts/1840075619545360

Yep! (Both are the same thing.) Give it a try, it's faster than npm. https://yarnpkg.com/

**Comment by dvampofo** [comment]
A  HUUGGE thank you Dan @gaearon  for walking me through this GH Pages project hosting/Create React App🙇 👐 !  I was getting frustrated understanding how Create React App works (or how to even file an issue), understanding CLIs and so on since I had no one experienced with this tool to talk but now I know more now than I did several hours ago.

Final question, so whenever I am building a future React app and have made changes to it (e.g. removing extra lines of code), do I always rebuild the entire project? Do I just run `npm run deploy` or `npm run build`  or <__insert new steps here__>?

**Comment by gaearon** [comment]
When you work locally you never need to rebuild. Just run `npm start`, open http://localhost:3000, and you should see your project. Whenever you change the code it will automatically rebuild on the fly.

If you want to **deploy** the new version (for example, after you've done working on a feature and it appears to work well), you just run `npm run deploy`.

You don't need to run `npm run build` because I included it as a step in `deploy`. If you look at `deploy` command in `package.json` you will notice it runs `npm run build` first.

I hope this helps!

**Pull request merged**
