### PR TITLE
resize option added on board

### PR DESCRIPTION
**Pull request by OnlyRefat**
I have added resize options @ the boards. You can look @ the gift the to see the changes.

[my Changes](http://www.tiikoni.com/tis/view/?id=8127315)

### CODE REVIEW

**Comment by dvampofo** [comment]
Thanks Rafi for the contribution @OnlyRefat ! I merged your commit, but I dont see the changes appearing. What is going on?

**Review by dvampofo — COMMENTED** [review]
Good but I dont see the changes on my master branch. What might the issue be?

**Comment by OnlyRefat** [comment]
Have you merged the latest master to gh-pages branch?? i think that will do the tricks :)

**Comment by dvampofo** [comment]
> Have you merged the latest master to gh-pages branch

@OnlyRefat How would I do that? Im searching on Google how to do that but I dont know which method I should follow.

**Comment by dvampofo** [comment]
A step-by-step list would be appreciated. I thought that the merge would show up in the master branch and then I could do a `git pull` and `npm run deploy` but your changes do not show up in any of the branches.

**Comment by OnlyRefat** [comment]
You have to run the following scripts from your master branch

```
 npm run deploy
```
and after that the new build file will be on you gh-pages branch and you will check it i think. 
NB. Dont forget to do hard refresh on your browser when checking if there is change or not. sometimes the page is cached on the browser.

**Comment by dvampofo** [comment]
Im new with using the command line and Git so I need some clarification. Is this the full steps that I should do?

1. `git clone <my repository with the your CSS merge>`
2. `npm run build`
3. `npm run deploy`

Since I didn't see your commits in my repo, I reverted your merge. Can you resubmit your PR? If the above steps are what I should do, then it should work (hopefully).

**Comment by OnlyRefat** [comment]
you can just run this following commands from your local project folder.

```
git pull
npm run deploy
```

**Comment by dvampofo** [comment]
Resubmit your PR so I can try your instructions again.

**Comment by OnlyRefat** [comment]
I have re submitted. You can check now.

**Comment by dvampofo** [comment]
Thanks and one last thing before I do the merge. 

For the resizing, can you 

- make the Note stretch vertically (see image below)...
- ...so that the scroll bar is hidden (just like I did with SAVE and X buttons) like you had in your gif (http://www.tiikoni.com/tis/view/?id=8127315)?

image

**Pull request merged**
